### ISSUE TITLE
Crash on Launch with only required Dependencies

### ISSUE THREAD

**Issue by el0c** [grondag/json-model-extensions#1]
Hey there, was excited to try your mod with my JSON models since I noticed in the wiki there seems to be an "emissive" option to use, but I couldn't get my client to launch with the mod installed!

As stated in the title, it seems the mod crashes with the latest Fabric API and Fabric Loader 
mappings: 1.14.2+build.7 
loader version: 0.4.8+build.155

https://pastebin.com/cJK3vXCQ

**Comment by grondag** [comment]
Thank you for letting me know.  Will take a look.

**Comment by grondag** [comment]
Just uploaded a fix to Curse.  Can also get it here:  https://github.com/grondag/json-model-extensions/releases/download/v1-alpha-3/jmx-0.1.0+alpha.21.jar

Note that docs are still WIP.  Thanks again for the report.
