### ISSUE TITLE
NPE is thrown when JMX data doesn't contain materials

### ISSUE THREAD

**Issue by alex5nader** [grondag/json-model-extensions#10]
When loading a JMX model defined without a materials element, as shown [here](https://github.com/grondag/json-model-extensions/blob/1.16/src/main/resources/assets/jmx/models/block/2/jmx_slab.json), a null pointer exception is thrown. This happens because when the extension data is being deserialized, JMX does not check whether or not these keys are present.

Crash report available [here](https://hastebin.com/eyozunekar.php) (generated via a mixin since the exception is normally caught).

**Comment by grondag** [comment]
Thank you for the issue report.  Are you planning to do a PR?

**Comment by alex5nader** [comment]
Yeah, I'm working on one.
