### ISSUE TITLE
Crash when paired with Indium

### ISSUE THREAD

**Issue by Carterpersall** [grondag/json-model-extensions#17]
Crash Report: https://pastebin.com/J3TmrHN2
Latest.log: https://pastebin.com/VGeh0p57
Only mods installed are Fabric API(0.45.0+1.18), Indium(1.0.2-alpha1+mc1.18), JSON Model Extensions(1.22.243), Mixintrace(1.1.0), and Sodium(0.4.0-alpha5+build.9).

**Comment by Phoenix-Starlight** [comment]
Can confirm too, JMX conflicts with Indium stable 1.171.

**Comment by supsm** [comment]
According to the wiki,
> JMX requires FREX v6 or higher

FREX is not compatible with indigo, therefore JMX will not be compatible with indium

**Comment by vrgtics** [comment]
but I go deeply, Just This One Single Mod causes us to crash.

![20220507-082035_1](https://user-images.githubusercontent.com/99676066/167231259-e9a9034c-df12-4414-8e04-1f76a92277b2.gif)

![VideoCapture_20220507-084624](https://user-images.githubusercontent.com/99676066/167231268-57e326ed-c0c5-4b3c-84f1-20921cc7da66.jpg)

![VideoCapture_20220507-084713](https://user-images.githubusercontent.com/99676066/167231277-56e9e344-388f-41f7-8f7e-3e644879ffb4.jpg)

**Comment by GhostIsBeHere** [comment]
Confirmed crash on 1.18.2 fabric

**Comment by supsm** [comment]
Bruh

**Comment by Carterpersall** [comment]
> According to the wiki,
> 
> > JMX requires FREX v6 or higher
> 
> FREX is not compatible with indigo, therefore JMX will not be compatible with indium

As this issue cannot be resolved due to a permanent incompatibility, I will close it.

**Comment by supsm** [comment]
[who says it’s permanent? 👀](https://github.com/spiralhalo/Plumbum)

**Comment by Carterpersall** [comment]
Well count me corrected then lol
