### ISSUE TITLE
RetexturedModelBuilder not working with items

### ISSUE THREAD

**Issue by Draylar** [grondag/json-model-extensions#2]
I can't seem to use `RetexturedModelBuilder` to copy a model from an item to another custom item. [Here](https://github.com/Draylar/jmx-testing) is an example project where the issue occurs.

**Re-producing:**
  1. registered 2 custom items, 1 of which has a working item model/texture
  2. called the RMB as I would for blocks:
`RetexturedModelBuilder.builder("minecraft:allium", "jmxtesting:my_item2")
				.mapSprite("block/allium", "block/allium")
				.completeItem();`
  3. loaded in after confirming the missing model error is gone from console

**Additional tests:**
I tried copying the custom item's model to the second unmodeled custom item, with the same result: no error, but no textures. Blocks work fine with this same setup, so I wonder if I made a sprite identifier error. 

**Logs/images:**
Here is an image of items 1 and 2, the second of which is supposed to have the allium model:
![image](https://user-images.githubusercontent.com/17728338/60403659-c45de200-9b65-11e9-84a7-9a670e6ebe4f.png). Pastebin of log is [here](https://pastebin.com/ajit93ZV)-- nothing off or wrong.

**Versions:**
 JMX: 0.2.3+build.45
 Minecraft: 1.14.3
 API: 0.3.0+build.187
 Loader: 0.4.8+build.155

I'm guessing it's some sort of silly "wrong namespace" error on my part, but haven't been able to figure it out. Thanks in advance!

**Comment by grondag** [comment]
I tracked this down to JMX not making generated item models transformable.  Is doable, just missed it.  Will address.

**Comment by grondag** [comment]
When you use this to replace the textures on a generated item model, are you expecting it to fully regenerate the model from the new sprite? Seems like it would have to because the shape of a generated item model is derived from the sprite.

 If so, this isn't so much retexturing an existing model as it is specifying a new generated model without the need for a JSON file. 

I still think it should work because it is confusing if it doesn't, but the implementation will be different.  Should be simpler, actually.

Just want to confirm your expectations before proceeding.

**Comment by grondag** [comment]
Also, there seems to be a bug with diffuse item lighting that JMX is causing.  I will log that separately.

**Comment by Draylar** [comment]
Yes, I'm just looking to create item models without a JSON file. In my use case, I don't _know_ what new items will be added (as they are created dynamically from a config file), so I'm unable to add a model to them in the assets folder.

My current approach for blocks is just:
  1. register a base block with model/texture
  2. add blocks dynamically (without models/textures) based on config
  3. copy base block model over to new blocks
  4. texture/hue new block colors with `ColorProviderRegistry`

My goal is to do this for items as well.

**Comment by grondag** [comment]
Okay.  Generated items should be relatively easy to support. 

Curious: JMX allows quads to be colorized directly instead of relying on colorIndex/BlockColorProvder but there is no way to recolor existing models. Would that be a worthwhile addition?

**Comment by Draylar** [comment]
Yes, absolutely. Would be nice if it made the "only color _this_ layer," process a bit easier as well-- doing it in the color provider is a bit of a pain.

**Comment by grondag** [comment]
Fixed with https://github.com/grondag/json-model-extensions/commit/b70b4956cb476eb00b2a5838a061583327be5666

Included in 0.2.5+ on maven, will be public soon.
