### ISSUE TITLE
[Suggestion] Model Rotations <90 degree

### ISSUE THREAD

**Issue by biom4st3r** [grondag/json-model-extensions#7]
Would it be possible to add rotating model smaller increments than 90 via blockstate?

**Comment by grondag** [comment]
It would be possible, but it's not something I want to do.

Currently JMX doesn't touch block state parsing - its a mess. Also, I'd prefer to import the JOML library vs use Mojang's vector/matrix/quaternion implementations, and that would make JMX kinda big.

Maybe at some other time.  If you don't mind a heavy dependency, Exotic Matter provides many more features as a model library, including rotations.

**Comment by grondag** [comment]
Forgot to add:  If someone wants to PR rotations for JMX, I'd happily consider that.  I just don't want to do them myself.
